# BookNuggets V2
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BookNuggets
# email: your-email@example.com

# this means to ignore newlines until "baseurl:"
description: >- 
  BookNuggets: A blog on the essential bits of information from books on Psychology, Investment, Data, Health, and other topics.

# baseurl: the subpath of your site, e.g. /blog
# url: the base hostname & protocol for your site, e.g. http://example.com

# For deployment:
baseurl: "/booknuggets"
url: "https://chrischow.github.io"

# For dev only:
# baseurl: ""
# url: ""


# twitter_username: jekyllrb
github_username:  chrischow

# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: css

# Disqus
comments: true

# Kramdown
kramdown:
    html_to_native: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
